#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 26 23:26:06 2020

@author: annayu

1423. Maximum Points You Can Obtain from Cards

Difficulty:Medium
There are several cards arranged in a row, 
and each card has an associated number of points.
 The points are given in the integer array cardPoints.

In one step, you can take one card from the beginning or from the end of the row. 
You have to take exactly k cards.

Your score is the sum of the points of the cards you have taken.

Given the integer array cardPoints and the integer k, 
return the maximum score you can obtain.

Example 1:
Input: cardPoints = [1,2,3,4,5,6,1], k = 3
Output: 12
Explanation: After the first step, your score will always be 1. 
However, choosing the rightmost card first will maximize your total score. 
The optimal strategy is to take the three cards on the right, 
giving a final score of 1 + 6 + 5 = 12.

Example 2:
Input: cardPoints = [2,2,2], k = 2
Output: 4
Explanation: Regardless of which two cards you take, your score will always be 4.

Example 3:
Input: cardPoints = [9,7,7,9,7,7,9], k = 7
Output: 55
Explanation: You have to take all the cards. Your score is the sum of points of all cards.

Example 4:
Input: cardPoints = [1,1000,1], k = 1
Output: 1
Explanation: You cannot take the card in the middle. Your best score is 1. 

Example 5:
Input: cardPoints = [1,79,80,1,1,1,200,1], k = 3
Output: 202
"""
cardPoints = [1,2,3,4,5,6,1]
k = 3

class Solution:
    # O(n*n)
    def maxScore(self, cardPoints, k): #too slow, did not pass time test
        
        if len(cardPoints) <= k:
            return sum(cardPoints)
        
        max_sum = cardPoints[0]
        
        for i in range(k+1):
            left_card = cardPoints[0:i]
            right_card = cardPoints[len(cardPoints)-(k-i) : len(cardPoints)]
            local_sum = sum(left_card) + sum(right_card)
            max_sum = max(max_sum,local_sum)
          
            
        return max_sum
    
    # O(n)
    #faster version
    def maxScore2(self, cardPoints, k):
        ans = sum_ = sum(cardPoints[:k])
        for i in range(k):
            sum_ += cardPoints[-i-1] - cardPoints[k-i-1]
            ans = max(ans, sum_)
        return ans